export const GET_GEMSTONES = 'GET_GEMSTONES';
export const GET_MELEE_DIAMONDS = 'GET_MELEE_DIAMONDS';
export const GET_LOOSE_DIAMONDS = 'GET_LOOSE_DIAMONDS';
export const GET_PRODUCT_DETAILS = 'CARATFLARE/GET_PRODUCT_DETAILS';
export const SET_PRODUCT_IMAGES = 'CARATFLARE/SET_PRODUCT_IMAGES';
export const SET_PRODUCT_VIDEOS = 'CARATFLARE/SET_PRODUCT_VIDEOS';
export const SET_360_PRODUCT_IMAGES = 'CARATFLARE/SET_360_PRODUCT_IMAGES';
export const GET_DIAMOND_FEATURES = 'CARATFLARE/GET_DIAMOND_FEATURES';
export const GET_MELEE_DIAMOND_FEATURES =
  'CARATFLARE/GET_MELEE_DIAMOND_FEATURES';
